nix/cli: Replace 'sub' and nix-shell with 'compleat' and a simple bash shell

diff --git a/assets/shell b/assets/shell
--- a/assets/shell
+++ b/assets/shell
@@ -16,7 +16,6 @@ mkdir -p "$BASE_DIR/.drvs"
 link="$(readlink -m "$BASE_DIR/.drvs/shell-$(cat "$BASE_DIR/.git-revision")-$(date +%s%N)")"
 
 nixPathArgs=("-f" "$BASE_DIR/paths.nix")
-nixShellArgs=()
 cmd=
 
 evalDefault='let pkgs = import <nixpkgs> { config.allowUnfree = true; }; in pkgs.lib.evalModules { modules = [ ./default.nix { _module.args = { inherit pkgs; }; } ]; }'
@@ -46,14 +45,16 @@ NIX_PATH="$(nix-path "${nixPathArgs[@]}" env | grep NIX_PATH | cut -d = --comple
 export NIX_PATH
 
 if [ -z "$cmd" ]; then
-  nix-instantiate "$@" --indirect --add-root "$link.drv" \
-    -E "$evalDefault" -A config.cli.build.nix-shell >/dev/null
-  TZ=UTC RELOADER_PID=$$ nix-shell "$link.drv" "$@" --fallback \
-    --indirect --add-root "$link"
+  nix-build --fallback --out-link "$link" --drv-link "$link.drv" \
+    -E "$evalDefault" -A config.cli.build.bashrc "$@"
+  if [ -a "$link" ]; then
+    RELOADER_PID=$$ $SHELL --rcfile "$link" -i
+  else
+    echo >&2 "Build failed"
+    exit 1
+  fi
 else
-  nix-build \
-    --fallback \
-    --out-link "$link" --drv-link "$link.drv" \
+  nix-build --fallback --out-link "$link" --drv-link "$link.drv" \
     -E "$evalDefault" -A config.cli.commands."$cmd".package
   if [ -x "$link/bin/$cmd" ]; then
     exec "$link/bin/$cmd" "$@"
